using System.Net;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TutoriaApi.Core.Interfaces;
using TutoriaApi.Infrastructure.Data;

namespace TutoriaApi.Infrastructure.Services;

/// <summary>
/// Hangfire jobs for study-plan emails. Plans are generated by tutoria-api
/// (Python) and persisted to StudyPlans; this side owns delivery:
/// - the full weekly plan right after generation (PlanEmailSent flag), and
/// - the 07:00 America/Sao_Paulo daily reminder with today's tasks (opt-in).
/// </summary>
public class StudyPlanEmailService : IStudyPlanEmailService
{
    private readonly TutoriaDbContext _context;
    private readonly IEmailService _emailService;
    private readonly ILogger<StudyPlanEmailService> _logger;

    public StudyPlanEmailService(
        TutoriaDbContext context,
        IEmailService emailService,
        ILogger<StudyPlanEmailService> logger)
    {
        _context = context;
        _emailService = emailService;
        _logger = logger;
    }

    private sealed record PlanDay(string Date, string Title, string Focus, List<PlanTask> Tasks);
    private sealed record PlanTask(string Description, int DurationMin);

    public async Task SendPendingPlanEmailsAsync()
    {
        // Safety window: never email plans older than 3 days (e.g. after downtime)
        var cutoff = DateTime.UtcNow.AddDays(-3);
        var pending = await _context.StudyPlans
            .Include(p => p.Course)
            .Where(p => !p.PlanEmailSent && p.CreatedAt > cutoff)
            .OrderBy(p => p.Id)
            .Take(50)
            .ToListAsync();
        if (pending.Count == 0) return;

        var studentIds = pending.Select(p => p.StudentId).Distinct().ToList();
        var students = await _context.Users
            .Where(u => studentIds.Contains(u.UserId))
            .ToDictionaryAsync(u => u.UserId);

        foreach (var plan in pending)
        {
            // Mark first so a crashing template can never spam the student
            plan.PlanEmailSent = true;

            if (!students.TryGetValue(plan.StudentId, out var student) ||
                string.IsNullOrWhiteSpace(student.Email))
            {
                continue;
            }

            try
            {
                var days = ParseDays(plan.DaysJson);
                var (html, text) = RenderWeek(plan.OverviewText, days, plan.Language);

                await _emailService.SendStudyPlanEmailAsync(
                    toEmail: student.Email,
                    toName: student.FirstName,
                    courseName: plan.Course?.Name ?? string.Empty,
                    bodyHtml: html,
                    bodyText: text,
                    dailyReminderEnabled: plan.DailyReminderOptIn,
                    languageCode: plan.Language);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to email study plan {PlanId} to {Email}",
                    plan.Id, student.Email);
            }
        }

        await _context.SaveChangesAsync();
        _logger.LogInformation("Study plan emails processed: {Count}", pending.Count);
    }

    public async Task SendDailyRemindersAsync()
    {
        var saoPaulo = GetSaoPauloTimeZone();
        var nowSp = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, saoPaulo);
        var today = nowSp.ToString("yyyy-MM-dd");

        // Monday of the current week in SP, expressed back in UTC like the Python side stores it
        var mondaySp = nowSp.Date.AddDays(-(int)((7 + (int)nowSp.DayOfWeek - 1) % 7));
        var weekStartUtc = TimeZoneInfo.ConvertTimeToUtc(
            DateTime.SpecifyKind(mondaySp, DateTimeKind.Unspecified), saoPaulo);

        var plans = await _context.StudyPlans
            .Include(p => p.Course)
            .Where(p => p.DailyReminderOptIn
                   && p.WeekStart >= weekStartUtc.AddHours(-26)
                   && p.WeekStart <= weekStartUtc.AddHours(26))
            .ToListAsync();
        if (plans.Count == 0) return;

        var studentIds = plans.Select(p => p.StudentId).Distinct().ToList();
        var students = await _context.Users
            .Where(u => studentIds.Contains(u.UserId))
            .ToDictionaryAsync(u => u.UserId);

        var sent = 0;
        foreach (var plan in plans)
        {
            if (!students.TryGetValue(plan.StudentId, out var student) ||
                string.IsNullOrWhiteSpace(student.Email))
            {
                continue;
            }

            var day = ParseDays(plan.DaysJson).FirstOrDefault(d => d.Date == today);
            if (day == null || day.Tasks.Count == 0) continue; // rest days stay quiet

            try
            {
                var tasksHtml = new StringBuilder();
                var tasksText = new StringBuilder();
                foreach (var task in day.Tasks)
                {
                    var safe = WebUtility.HtmlEncode(task.Description);
                    var duration = task.DurationMin > 0 ? $" <span style=\"color:#999999;\">({task.DurationMin} min)</span>" : "";
                    tasksHtml.Append($"<p style=\"margin:4px 0;font-size:14px;color:#333333;\">☐ {safe}{duration}</p>");
                    tasksText.AppendLine($"- {task.Description}" + (task.DurationMin > 0 ? $" ({task.DurationMin} min)" : ""));
                }

                await _emailService.SendStudyPlanDailyReminderEmailAsync(
                    toEmail: student.Email,
                    toName: student.FirstName,
                    courseName: plan.Course?.Name ?? string.Empty,
                    dayTitle: string.IsNullOrWhiteSpace(day.Title) ? day.Focus : day.Title,
                    tasksHtml: tasksHtml.ToString(),
                    tasksText: tasksText.ToString(),
                    languageCode: plan.Language);
                sent++;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed daily study reminder for plan {PlanId}", plan.Id);
            }
        }

        _logger.LogInformation("Daily study reminders sent: {Sent}/{Plans}", sent, plans.Count);
    }

    private static List<PlanDay> ParseDays(string daysJson)
    {
        var result = new List<PlanDay>();
        try
        {
            using var doc = JsonDocument.Parse(daysJson);
            foreach (var dayEl in doc.RootElement.EnumerateArray())
            {
                var tasks = new List<PlanTask>();
                if (dayEl.TryGetProperty("tasks", out var tasksEl) && tasksEl.ValueKind == JsonValueKind.Array)
                {
                    foreach (var taskEl in tasksEl.EnumerateArray())
                    {
                        var description = taskEl.TryGetProperty("description", out var d) ? d.GetString() ?? "" : "";
                        if (string.IsNullOrWhiteSpace(description)) continue;
                        var duration = taskEl.TryGetProperty("duration_min", out var m) && m.TryGetInt32(out var minutes)
                            ? minutes : 0;
                        tasks.Add(new PlanTask(description, duration));
                    }
                }
                result.Add(new PlanDay(
                    dayEl.TryGetProperty("date", out var dateEl) ? dateEl.GetString() ?? "" : "",
                    dayEl.TryGetProperty("title", out var titleEl) ? titleEl.GetString() ?? "" : "",
                    dayEl.TryGetProperty("focus", out var focusEl) ? focusEl.GetString() ?? "" : "",
                    tasks));
            }
        }
        catch (JsonException)
        {
            // malformed plan JSON — email the overview alone
        }
        return result;
    }

    private static (string Html, string Text) RenderWeek(string overview, List<PlanDay> days, string language)
    {
        var html = new StringBuilder();
        var text = new StringBuilder();

        var safeOverview = WebUtility.HtmlEncode(overview);
        html.Append($"<p style=\"font-size:14px;color:#333333;\">{safeOverview}</p>");
        text.AppendLine(overview).AppendLine();

        var restLabel = language.ToLower() switch
        {
            "en" => "Rest day 🌴",
            "es" => "Día de descanso 🌴",
            _ => "Dia de descanso 🌴",
        };

        foreach (var day in days)
        {
            var safeTitle = WebUtility.HtmlEncode(day.Title);
            var safeFocus = WebUtility.HtmlEncode(day.Focus);
            var dateLabel = day.Date;
            if (DateTime.TryParse(day.Date, out var parsed))
                dateLabel = parsed.ToString("dd/MM (ddd)");

            html.Append("<div style=\"border-left:4px solid #5ce1e6;background:#f8feff;border-radius:8px;padding:12px 16px;margin:10px 0;\">");
            html.Append($"<p style=\"margin:0;font-size:12px;color:#0e7490;font-weight:bold;\">{WebUtility.HtmlEncode(dateLabel)}</p>");
            html.Append($"<p style=\"margin:2px 0 6px 0;font-size:15px;font-weight:bold;color:#1a1a1a;\">{safeTitle}</p>");
            text.AppendLine($"{dateLabel} — {day.Title}");

            if (day.Tasks.Count == 0)
            {
                html.Append($"<p style=\"margin:0;font-size:13px;color:#555555;\">{restLabel}</p>");
                text.AppendLine($"  {restLabel}");
            }
            else
            {
                if (!string.IsNullOrWhiteSpace(day.Focus))
                    html.Append($"<p style=\"margin:0 0 6px 0;font-size:13px;color:#555555;\">{safeFocus}</p>");
                foreach (var task in day.Tasks)
                {
                    var safe = WebUtility.HtmlEncode(task.Description);
                    var duration = task.DurationMin > 0 ? $" <span style=\"color:#999999;\">({task.DurationMin} min)</span>" : "";
                    html.Append($"<p style=\"margin:3px 0;font-size:13px;color:#333333;\">☐ {safe}{duration}</p>");
                    text.AppendLine($"  - {task.Description}" + (task.DurationMin > 0 ? $" ({task.DurationMin} min)" : ""));
                }
            }
            html.Append("</div>");
            text.AppendLine();
        }

        return (html.ToString(), text.ToString());
    }

    private static TimeZoneInfo GetSaoPauloTimeZone()
    {
        try
        {
            return TimeZoneInfo.FindSystemTimeZoneById("America/Sao_Paulo");
        }
        catch (TimeZoneNotFoundException)
        {
            return TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time");
        }
    }
}
