namespace TutoriaApi.Core.Entities;

/// <summary>
/// AI-written daily briefing per university, generated by the tutoria-worker
/// nightly job from the previous day's chat/topic/quiz data (only when there
/// was new activity). Shown as the hero card on the analytics dashboard.
/// </summary>
public class DailyAISummary : BaseEntity
{
    public int UniversityId { get; set; }
    public University? University { get; set; }

    /// <summary>The day the summary describes (not the generation day).</summary>
    public DateOnly Date { get; set; }

    public required string SummaryText { get; set; }

    /// <summary>JSON array of short bullet highlights.</summary>
    public string? HighlightsJson { get; set; }

    public string? Provider { get; set; }
}
